title: George Burbano # your name (or website title) here
logo: "/images/Date_night.jpg?raw=true" # your photo (or logo) here
description:
Bio
<br>
hey


<br>
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
